Fixed axios require in the pkgcontrol package
Fixes error:
Cannot find module 'axios' from '.nvm/v0.10.38/lib/node_modules/codebox/packages/pkgcontrol/src'